imageGeneratorPort: 9000
ImageProperties:
  # BackgroundImage: none
  BackgraundColor:
    Red: 44
    Green: 154
    Blue: 100
  ImageWigth: 1920
  ImageHeight: 1080   
  # Text: "Hello from ImageBot"       
  # TextColor: black